# This is a list of official hero names in order of release date. The
# first set of heroes from Abathur to Zeratul were available on
# release. The rest are listed in chronological order of release. New
# heroes should be added to the end of the list.
HEROES = [
    "Abathur",
    "Arthas",
    "Diablo",
    "E.T.C.",
    "Falstad",
    "Gazlowe",
    "Illidan",
    "Kerrigan",
    "Malfurion",
    "Muradin",
    "Nazeebo",
    "Nova",
    "Raynor",
    "Sgt. Hammer",
    "Sonya",
    "Stitches",
    "Tassadar",
    "Tyrael",
    "Tyrande",
    "Uther",
    "Valla",
    "Zeratul",
    "Tychus",
    "Li Li",
    "Brightwing",
    "Murky",
    "Zagara",
    "Rehgar",
    "Chen",
    "Azmodan",
    "Anub'arak",
    "Jaina",
    "Thrall",
    "The Lost Vikings",
    "Sylvanas",
    "Kael'thas",
    "Johanna",
    "The Butcher",
    "Leoric",
    "Kharazim",
    "Rexxar",
    "Lt. Morales",
    "Artanis",
    "Cho",
    "Gall",
    "Lunara",
    "Greymane",
    "Li-Ming",
    "Xul",
    "Dehaka",
    "Tracer",
    "Chromie",
    "Medivh",
    "Guldan",
    "Auriel",
    "Alarak",
    "Zarya",
    "Samuro",
    "Varian",
    "Ragnaros",
    "Zul'jin",
    "Valeera",
    "Lúcio",
]
